name: Run API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Register Users API Tests
        run: newman run tests/RegisterUsers_API_Tests.postman_collection.json --delay-request 1000 --reporters cli,junit --reporter-junit-export junit-report-registerusers.xml

      - name: Run Get User API Tests
        run: newman run tests/GetUsers_API_Tests.postman_collection.json --delay-request 1000 --reporters cli,junit --reporter-junit-export junit-report-getusers.xml

      - name: Run Update User API Tests
        run: newman run tests/UpdateUser_API_Tests.postman_collection.json --delay-request 1000 --reporters cli,junit --reporter-junit-export junit-report-updateuser.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            junit-report-registerusers.xml
            junit-report-getusers.xml
            junit-report-updateuser.xml
