name: Run API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run tests/user_register.postman_collection.json --delay-request 1000
